// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CountdownController from "./countdown_controller"
application.register("countdown", CountdownController)

import FingerprintController from "./fingerprint_controller"
application.register("fingerprint", FingerprintController)

import LoginFormController from "./login_form_controller"
application.register("login-form", LoginFormController)

import PasswordController from "./password_controller"
application.register("password", PasswordController)

import SearchController from "./search_controller"
application.register("search", SearchController)
